.github/workflows/ci.yml
.github/workflows/release.yml

Setting up CI cache

---

.github/workflows/release.yml

Setting up Release workflow

---

extension/background.ts
gui/src/components/Connections.tsx
gui/src/components/HomePage.tsx
gui/src/components/Txs.tsx
tauri/src/commands.rs
tauri/src/context/inner.rs
tauri/src/ws.rs

Connections List revamp

---

extension/background.ts
gui/src/components/Connections.tsx
tauri/Cargo.toml
tauri/src/app.rs
tauri/src/context/inner.rs
tauri/src/context/network.rs
tauri/src/context/wallet.rs
tauri/src/db.rs
tauri/src/ws.rs

* Configures `background.js` to automatically close websocket connections once tabs are closed
* Improves app connections UI (group by tab ID, show tab title)

Disconnect from WS on tab close

---

extension/background.ts
extension/content_script/index.ts
extension/content_script/injectInpageScript.ts
extension/content_script/providerForward.ts
extension/global.d.ts
extension/inpage.ts
extension/manifest.json
extension/options/index.html
extension/options/index.ts
extension/package.json
extension/settings.ts
yarn.lock

Extension settings page

---

extension/background.ts

extension now retries connection with an exponential backoff

---

gui/package.json
gui/src/components/Base/Dropdown.tsx
gui/src/components/Settings/QuickAccountSelect.tsx
gui/src/components/Settings/QuickNetworkSelect.tsx
yarn.lock

Replaced with these: https://tailwindui.com/components/application-ui/elements/dropdowns

Removing flowbite's dropdown

---

tauri/src/rpc.rs

This finally closes #7 and #61

Message Signing with eth_sign and eth_signTypedData_v4

---

gui/src/components/Settings/QuickAccountSelect.tsx
gui/src/components/Settings/Wallet.tsx

Fixing some bugs in the address dropdown + form

---

README.md

Download instructions

---

tauri/src/context/network.rs

Removing my free Alchemy API key from this

using public RPCs for mainnet and goerli

---

gui/src/components/Settings/Wallet.tsx
tauri/src/commands.rs
tauri/src/context/wallet.rs
tauri/src/error.rs

mnemonic validation and UI errors

---

tauri/src/rpc.rs

Metamask's errors:
Our new errors:

Better error handling of RPC requests

---

Cargo.lock
tauri/Cargo.toml
tauri/src/error.rs
tauri/src/main.rs
tauri/src/rpc.rs
tauri/tauri.conf.json

Using fix-path-env

---

Cargo.lock
deny.toml

Everything seems to work fine.

Upgrade Tauri

---

gui/src/components/Balances.tsx
gui/src/components/Contracts.tsx
gui/src/components/CopyToClipboard.tsx
gui/src/components/Txs.tsx

A small change, a big quality of life improvement. Plus, the component `CopyToClipboard` can be easily used anywhere. You don't need to specify the text you want to copy to the clipboard.

Clicking on addresses, hashes and values copies to clipboard

---

Cargo.lock
tauri/Cargo.toml
tauri/src/app.rs

Installs `https://github.com/tauri-apps/tauri-plugin-window-state` and handles  `tauri::WindowEvent::CloseRequested` event to prevent the app from closing when the window is closed.

Save window positions and sizes

---

.eslintrc.js
.github/workflows/ci-rust.yml
Justfile
tauri/src/app.rs
tauri/src/error.rs

to save us the effort, now we can just trust that this isn't made
@gabrielpoca not sure about you, but usually when I know the CI will catch stuff, I'll approve the PR in the meantime, since that means the other person won't need to wait another round.
let me know if there are other things we could automate

Let the CI complain about console.log/dbg calls

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Using https://github.com/marketplace/actions/release-drafter

Setting up release-drafter

---

gui/src/components/ContextMenu.tsx
gui/src/components/HomePage.tsx
gui/src/components/ProviderTheme.tsx
gui/src/components/Txs.tsx

* Improved transaction list design
* added icons for calls / deploys / received transactions
* removed the arbitrary panel around the HomePage, everything seems a bit cleaner now

Better TXs list

---

.github/release-drafter.yml
gui/src/components/ProviderWallets.tsx

Related: https://github.com/release-drafter/release-drafter/pull/1302

Fixing release drafter

---

.github/workflows/release.yml

This finally unblocks releases

Setting up libsodium on windows

---

gui/src/components/QuickAddressSelect.tsx
gui/src/components/Settings/HDWalletForm.tsx
gui/src/components/SettingsWallets.tsx
gui/src/types.ts
tauri/src/app.rs
tauri/src/wallets/commands.rs
tauri/src/wallets/error.rs
tauri/src/wallets/hd_wallet.rs
tauri/src/wallets/json_keystore_wallet.rs
tauri/src/wallets/mod.rs
tauri/src/wallets/utils.rs
tauri/src/wallets/wallet.rs

Support for HD Wallets

---

gui/src/components/Modal.tsx

bugfix: modals in forms were broken

---

Cargo.lock
crates/rpc/Cargo.toml
crates/rpc/src/error.rs
crates/rpc/src/lib.rs
crates/tracing/src/lib.rs
crates/ws/src/server.rs
extension/background.ts
gui/src/components/Peers.tsx

This switches from an exponential backoff to a constant backoff
Hopefully that's enough to make reconnections seem more comfortable

Improving extension reconnection logic

---

gui/src/components/Account.tsx
gui/src/components/AddressView.tsx

Also slightly tweaks the Account view, especially in small viewports.
closes #339

Fixing account copy-to-clipboard button

---

gui/src/components/Settings/Wallets.tsx

Adds a wallet type chip to the wallet settings accordion

---

extension/src/inpage/provider.ts

As discussed in #346 , some of the fields that carried over from the Metamask provider are not necessary to be EIP-1193 compliant

Removes more unneeded public APIs from window.ethereum

---

extension/package.json
extension/src/inpage/index.ts
yarn.lock

Implementing EIP-6963. 
Feel free to modify the `icon` – just using the GH org one lol.

feat: eip-6963

---

Cargo.lock
crates/settings/src/lib.rs
gui/src/components/Settings/General.tsx
gui/src/types.ts

This is a requirement for #332

Adding etherscan API key setting

---

extension/package.json
extension/src/background/index.ts
extension/src/content-script/index.ts
extension/src/inpage/index.ts
extension/src/inpage/provider.ts
yarn.lock

This one has been eluding me for a few weeks now, but should finally bring some more stability to the extension connection.
Seems to be a chromium bug first described here: https://groups.google.com/a/chromium.org/g/chromium-extensions/c/gHAEKspcdRY?pli=1
Metamask applies a similar workaround here: https://github.com/MetaMask/metamask-extension/blob/64aef2a1c9f5b46fdf2aa52f8d94750dc9873496/app/scripts/contentscript.js#L642-L652

Fix a long-standing bug where cs <> bg communication would sometimes fail

---

gui/package.json
gui/src/types.ts
yarn.lock

Solution for this issue: https://github.com/iron-wallet/iron/issues/364

Refine mnemonic schema

---

.eslintrc.js
extension/src/inpage/utils.ts
gui/src/hooks/useNoticeAlchemyKeyMissing.tsx

Adds no-confusing-void-expression to eslint

---

bin/iron/src/app.rs

This call is optional and not necessary.

Remove call to save_window_state

---

Cargo.toml
Justfile
extension/package.json
extension/scripts/build.sh
extension/src/public/manifest-chrome.json
extension/src/public/manifest-firefox.json
gui/package.json
package.json

Source of truth for app version is now solely `Cargo.toml`

Source of truth for app version is now solely Cargo.toml

---

bin/iron/src/app.rs
bin/iron/src/commands.rs
gui/src/hooks/useNoticeNewVersion.tsx
gui/tsconfig.json

I accidentally broke this notice after #412

Fix: new version notice regression

---

crates/broadcast/src/lib.rs
crates/forge/src/commands.rs
crates/forge/src/manager.rs
crates/rpc/src/send_transaction.rs
crates/settings/src/utils.rs
gui/src/components/Calldata.tsx
gui/src/components/Dialogs/TxReview.tsx
gui/src/components/Txs.tsx
gui/src/components/index.ts

add json view to tx review dialog

---

crates/sync/anvil/src/tracker.rs

This small tweak makes it so the UI updates immediatelly once anvil is shutdown, emptying the transactions & contracts list

Reset anvil tracker on every loop iteration

---

crates/forge/src/manager.rs
crates/forge/src/watcher.rs
crates/ws/src/server.rs

Prevent forge watcher from crashing with invalid directories

---

gui/src/App.tsx
gui/src/components/Toast.tsx
gui/src/hooks/useNoticeAlchemyKeyMissing.tsx
gui/src/hooks/useNoticeNewVersion.tsx
gui/src/store/contracts.ts

Showing explicit error when etherscan key not found

---

CONTRIBUTING.md
README.md

Fixes contribution guide

---

bin/iron/src/app.rs
bin/iron/src/dialogs.rs
bin/iron/src/main.rs
crates/dialogs/src/error.rs
crates/dialogs/src/handle.rs
crates/dialogs/src/lib.rs
crates/dialogs/src/utils.rs
crates/rpc/src/send_transaction.rs
crates/rpc/src/sign_message.rs
crates/types/src/ui_events.rs
crates/wallets/src/wallets/hd_wallet.rs
crates/wallets/src/wallets/json_keystore_wallet.rs

Handling dialog window close events

---

bin/iron/src/app.rs
crates/http/src/lib.rs
crates/http/src/routes/rpc.rs
crates/rpc/src/error.rs
crates/rpc/src/lib.rs
crates/wallets/src/wallet.rs
crates/ws/src/server.rs
extension/src/inpage/provider.ts

Correctly capture "User Rejected Request" and "Unauthorized" errors

Better RPC errors handling

---

.github/workflows/release.yml

This is the last detail to close #281

Auto publishing chrome extension

---

Cargo.lock
Cargo.toml
crates/wallets/Cargo.toml

https://github.com/summa-tx/coins/pull/126 has landed, but I needed to still fork and downgrade the version number to trick ethers-signers into accepting it

Updating coins-ledger

---

Cargo.lock
Cargo.toml
crates/rpc/src/error.rs
crates/rpc/src/send_transaction.rs

The new upstream version seems to be breaking
https://github.com/summa-tx/coins/issues/128

Ledger retry

---

CONTRIBUTING.md

A typo was found on the `CONTRIBUTING.md` file. I change it to be the same command as in `package.json`

Change "yarn extension:dev" to "yarn ext:dev"

---

crates/ws/src/server.rs
extension/src/background/index.ts
extension/src/content-script/index.ts

It turns out the standard ping/pong ws messages are not enough to keep the connection alive

Fixes ping-pong keepalive logic

---

gui/src/components/Account.tsx
gui/src/components/Navbar.tsx
gui/src/components/Sidebar.tsx

navbar & accounts layout update

---

Cargo.toml
Justfile

https://github.com/tauri-apps/tauri/issues/8403

Fixing live reload

---

gui/src/components/Dialogs/Layout.tsx
gui/src/components/Dialogs/TxReview.tsx

Action buttons now stick to the bottom

Better layout for TxReviewDialog

---

gui/src/components/DevBuildNotice.tsx

Better DevBuildNotice

---

.gitignore
Cargo.lock
Cargo.toml
bin/iron/Cargo.toml
bin/iron/build.rs
crates/token-list/Cargo.toml
crates/token-list/src/lib.rs
crates/wallets/src/wallet.rs
crates/wallets/src/wallets/mod.rs
crates/wallets/src/wallets/private_key.rs

This PR addresses the initial steps of this issue: https://github.com/iron-wallet/iron/issues/283
Why?
- As an extra security measure, Iron Wallet should show crypto icons from a verified list fetched from a reliable source. Currently the chosen source is: https://gateway.ipfs.io/ipns/tokens.uniswap.org
How?
- Creation of a tokenlist crate that fetches and parses the extensive information coming from the source
- Creation of a list.json file built at build time
- Parse the information in a format that benefits future implementations
- Add tokenlist to .gitignore
Currently, it creates the list.json file in the iron/bin directory, as shown in this screenshot:

Add tokenlist crate and create list.json

---

gui/src/components/ABIForm.tsx
gui/src/components/ABIForm/index.tsx

quickfix for #623 for the time being

Working with array fields

---

Cargo.lock
Cargo.toml
bin/Cargo.toml
bin/src/app.rs
crates/abis/Cargo.toml
crates/abis/src/commands.rs
crates/abis/src/lib.rs
gui/src/components/ABIForm/ABIInput.tsx
gui/src/components/ABIForm/index.tsx
yarn.lock

This uses alloy-dyn-abi to more inteligently parse function arguments in order to both validate them and put them in a format that will be parsed correctly by transaction providers

Smarter ABI input parsing

---

gui/src/routes/_home.home/contracts.lazy.tsx
gui/src/store/contracts.ts

Ability to filter contracts on UI

---

extension/scripts/build.sh
extension/src/content-script/index.ts
extension/src/inpage/index.ts
extension/src/inpage/utils.ts
extension/tsconfig.json

The two extensions could coexist, but would get into conflicts by incorrectly sharing communication channels, since they were name-based

Fixes conflicts between ethui and ethui-dev extensions

---

gui/src/components/ABIForm/ABIInput.tsx
gui/src/components/ABIForm/ABIItemForm.tsx
gui/src/components/ABIForm/index.tsx
gui/src/routes/_dialog.dialog/tx-review.$id.lazy.tsx

Ability to make raw calls on ABIItemForm

---

packages/form/src/AbiForm.tsx
packages/form/src/utils.tsx

Ability to set default calldata and ether value in AbiForm

@ethui/form: default values

---

crates/dialogs/src/presets.rs
crates/rpc/src/methods/send_transaction.rs
gui/src/components/ABIForm/ABIItemForm.tsx
gui/src/components/Datapoint.tsx
gui/src/hooks/useDialog.ts
gui/src/routes/_dialog.dialog/tx-review.$id.lazy.tsx
packages/form/src/AbiForm.tsx

The final piece of the puzzle that was #501

Ability to edit TX in realtime

---

gui/src/store/contracts.ts
packages/types/index.ts

Fix: filter contracts by alias

---

crates/rpc/src/methods/token_add.rs

This PR fixes some clippy warnings that got lost from a previous merge.

Fix clippy warnings on token_add

---

.sqlx/query-008400ee1a9cb21eda246d7ea2cc8e3440d4c8c27c8abd40fd16b6539956b935.json
.sqlx/query-5730e68dd4e4a3b4ea9fee54ff25d517799d42a778de69b7766b7f9370a104a7.json
.sqlx/query-6619b8aad8df7e0bdd52e4eb8f73d9c328496fdc8990b062cf7acfad22031212.json
.sqlx/query-7a9739c7db149527c35f8f73127b5fc275c88200aad9338654eee74f66149de1.json
.sqlx/query-94ae3bd2454152a0e49880edb26fda7f70c74089b1bffc889737b7bf73940ff1.json
.sqlx/query-c00ba0ff7d0138a8a83613ed6b271a8acd148c0e599d9e6629293e40e761de6e.json
.sqlx/query-f0095c03aa5c43439526333d4c8fa585642288a3919088202822138449e97055.json
Cargo.lock
Cargo.toml
crates/db/src/queries/erc1155.rs
deny.toml

- update `time`
- deal with new clippy error
- update deny.toml config

Fixes to build after a long hiatus

---

README.md

Docs (README)

---

gui/src/routes/home/_l/connections.tsx

It was not showing "global" options properly

Fixing connections dropdown

---

gui/src/components/Settings/Wallet/HDWallet.tsx
gui/src/routes/home/_l/settings/general.tsx
packages/ui/components/form.tsx

- Better placement of `FormMessage`, to not push content up/down as errors appear
- Better submit button icon and disabled state
- memoize external calls to speed up zod validation

Improving forms

---

bin/src/dialogs.rs
bin/src/utils.rs
packages/ui/stories/click-to-copy.stories.tsx

Fix title bars back in Linux, and applies same fix to dialog title bars

Fixes title bars (part 2)

---

gui/src/routes/__root.tsx
packages/ui/.storybook/preview.tsx
packages/ui/components/click-to-copy.tsx
packages/ui/components/providers/clipboard-provider.tsx

This makes it easier to inject tauri's clipboard into the UI

Adding a clipboard provider

---

gui/src/routes/dialog/_l.tsx

Fix dark mode not being respected in dialogs

---

gui/src/components/QuickWalletSelect.tsx
gui/src/components/Settings/Wallets.tsx
gui/src/components/WalletView.tsx
gui/src/routes/home/_l/settings/_l/networks/_l/index.tsx
gui/src/routes/onboarding/_l/wallets/_l/index.tsx
packages/ui/tailwind.config.js
packages/ui/tailwind.css

Wallet icons

---

.gitignore
.mise.toml
.mise/tasks/setup
package.json

Fixing rust-target

---

gui/src/routes/home/_l/contracts/_l/index.tsx
packages/demo/src/wagmi.generated.ts
packages/ui/components/form.tsx

Fixing contract add dialog

---

gui/src/components/AppNavbar.tsx
gui/src/components/AppSidebar.tsx
gui/src/components/TransferForm.tsx
gui/src/routes/dialog/_l/wallet-unlock.$id.tsx
gui/src/routes/home/_l.tsx
gui/src/routes/home/_l/contracts/_l/index.tsx
packages/demo/src/components/app-sidebar.tsx
packages/demo/src/routes/__root.tsx
packages/ui/components/form.tsx
packages/ui/components/shadcn/sidebar.tsx

Fix button spacings

---

bin/src/system_tray.rs

Fixes app crash when hiding already closed window

---

bin/src/app.rs
bin/src/utils.rs
crates/broadcast/src/lib.rs

Why:
* Solves #828
How:
* By catching the `Reopen` event and triggering a window

Handle Reopen event to show window when click in MacOS dock icon

---

Cargo.lock
crates/connections/Cargo.toml
crates/connections/src/ctx.rs
crates/connections/src/lib.rs
crates/connections/src/permissions.rs
crates/rpc/src/commands.rs
crates/rpc/src/lib.rs
crates/tracing/src/lib.rs
deny.toml

This is completely non-interactive for now. Arguably for developer workflows there is much less benefit in having more  interaction when setting up a connection, though this may be revisited
for now it solves the very annoying problem of rainbowkit not auto-connecting after a browser refresh

Initial support for EIP-2255 (Wallet permissions)

---

CONTRIBUTING.md
README.md

Simplifies a lot of the setup, removes now-unnecessary info
not 100% sure it fully solves #838 , but sure is a good step in that direction

Updates readme and contribution guide

---

gui/src/components/ContractCallForm.tsx
gui/src/routes/dialog/_l/chain-add.$id.tsx
gui/src/routes/dialog/_l/erc1155-add.$id.tsx
gui/src/routes/dialog/_l/erc20-add.$id.tsx
gui/src/routes/dialog/_l/erc721-add.$id.tsx
gui/src/routes/dialog/_l/msg-sign.$id.tsx
gui/src/routes/home/_l/settings/_l/networks/_l/$name.edit.tsx
gui/src/routes/home/_l/settings/_l/networks/_l/new.tsx

Why:
* Solves #836
How:
* Adding a loading spinner and disabling buttons while
submitting
* Reordering buttons so the cancel option appears first in the Networks
tab

Apply loading states and disabled to dialogs

---

packages/demo/contracts/NFT.sol
packages/demo/contracts/TestCallsUpgradeable.sol
packages/demo/contracts/Token.sol
packages/demo/foundry.toml
packages/demo/remappings.txt
packages/demo/script/DevDeploy.s.sol
packages/demo/soldeer.lock
packages/demo/src/wagmi.generated.ts

Closes #891 
I don't think we need to add this one to the UI of the demo itself

Add an upgradeable contrat to the demo app

---

crates/broadcast/src/lib.rs
crates/rpc/src/lib.rs
crates/rpc/src/methods/chain_add.rs
crates/rpc/src/methods/chain_update.rs
crates/rpc/src/methods/mod.rs
gui/src/components/QuickNetworkSelect.tsx
gui/src/routeTree.gen.ts
gui/src/routes/dialog/_l.tsx
gui/src/routes/dialog/_l/chain-switch.$id.tsx
gui/src/store/useNetworks.tsx
packages/types/index.ts

rework of wallet_updateEthereumChain

---

.github/workflows/rust.yml
bin/src/app.rs

The original code was compiling sqlx-cli from source, which would take over 2 minutes of CI time

using cargo-binstall sqlx instead of compiling from source

---

bin/src/commands.rs

Why:
* If the proxy is `EIP1167`, Etherscan returns the
implementation's contract name and ABI. In this case, we want to show
the proxy contract's name as `EIP1167`
How:
* Hardcoding the name for the proxy contract to be `EIP1167`

Use EIP1167 as proxy name

---

gui/src/components/ContractCallForm.tsx

Why:
* Current logic would only allow `view` functions or `raw` calls to be
made
How:
* Reversing the `if` condition so the `else` would also work for write
funtions

Fix contract call form

---

gui/package.json
gui/src/components/Settings/Wallets.tsx
yarn.lock

Clean up some old storybook dependencies

Remove old storybook deps

---

.github/workflows/release-drafter.yml

See https://github.com/release-drafter/release-drafter/issues/1425

Prevent release drafter from creating duplicate drafts

---

.github/workflows/rust.yml

https://github.com/EmbarkStudios/cargo-deny-action/issues/94

Fixing cargo-deny workflows

---

gui/src/routes/home/_l/transactions.tsx

These were a bit too intrusive on the initial page load

Tweaking transactions page animations

---

gui/package.json
gui/src/components/ContractCallForm.tsx
gui/src/components/HashView.tsx
gui/src/routes/home/_l/transactions.tsx
gui/src/routes/home/_l/transfer/_l.erc20.tsx
gui/src/routes/home/_l/transfer/_l.eth.tsx
packages/types/index.ts
yarn.lock

better output for transaction calls

---

bin/capabilities/main.json
crates/dialogs/src/presets.rs
crates/rpc/src/methods/sign_message.rs
gui/package.json
gui/src/components/AnimatedOutlet.tsx
gui/src/components/JsonView.tsx
gui/src/main.css
gui/src/routes/dialog/_l.tsx
gui/src/routes/dialog/_l/msg-sign.$id.tsx
yarn.lock

Json view for message signatures

---

gui/src/routes/home/_l/connections.tsx
packages/types/index.ts

Why:
* Fixes #1221
How:
* Stringifying the value passed to the `Select` component in order to
correctly display the selected option. The feature was working as
intended, it was just a visual bug with the dropdown

Fix bug with Connections not updating to the selected network

---

bin/src/windows/main.rs
crates/settings/src/init.rs
crates/settings/src/onboarding.rs
gui/src/components/AppSidebar.tsx
gui/src/routes/home/_l/onboarding.tsx
packages/types/settings.ts

Most of the changes are about making `onboarding.hidden` automatically turn false whenever we add new onboarding items. this will mean new features can get easily highlighted to existing users

Adds etherscan API key to onboarding steps

---

gui/src/components/Breadcrumbs.tsx
gui/src/routes/home/_l/settings/_l.tsx
gui/src/routes/home/_l/transfer/_l.tsx

Fixes breadcrumbs linking to empty pages

---

gui/package.json
gui/src/components/QuickFastModeToggle.tsx
gui/src/routes/home/_l/settings/_l/general.tsx
packages/form/package.json
yarn.lock

Also improves switch styling a bit
Partially fixes #1228

Replaces checkboxes with switches

---

gui/src/components/Settings/Wallet/PrivateKey.tsx

This was probably some weird find/replace mishap

Small copy fix

---

gui/src/components/AppSidebar.tsx

WIP - needs to be tested on a macos machine

adjust sidebar top padding on macos

---

.mise/tasks/setup

Related to #1269, fixes some problems by:
- Replacing `red` usage with `echo`
- Correcting install name

Fixing some setup problems

---

gui/src/components/AppSidebar.tsx
gui/src/routeTree.gen.ts
gui/src/routes/home/_l/settings/_l/about.tsx

Shows app version on UI

---

Cargo.lock
crates/rpc/Cargo.toml
crates/rpc/src/error.rs
crates/rpc/src/lib.rs
crates/rpc/src/methods/ethui/abi_for_contract.rs
crates/rpc/src/methods/ethui/mod.rs
crates/rpc/src/methods/mod.rs

This is a prototype to communicate ABIs with the explorer, and provide some synergy between the two sides

Prototype: ethui_get_contract_abi RPC endpoint

---

gui/package.json
package.json
yarn.lock

Fixing error on BigInt parsing

---

gui/src/routes/home/_l/transactions.tsx

Infinite scroll was not behaving properly

Fixes infinite scroll bug

---

gui/package.json
gui/src/components/Transactions/TransactionsTable.tsx
nix/package.nix
pnpm-lock.yaml

Highlight addresses explorer

---

gui/package.json
gui/src/routes/home/_l/settings/_l/networks/_l/$name.edit.tsx
gui/src/routes/home/_l/settings/_l/networks/_l/new.tsx
nix/package.nix
packages/types/network.ts
pnpm-lock.yaml

this makes it possible to remove optional network fields when editing them

fix: nullable network fields

---

gui/src/components/Topbar.tsx

Add navigation buttons top bar

---

gui/src/hooks/useAllAddresses.ts
gui/src/routes/home/_l/explorer/_l/addresses/index.tsx

Explorer addresses tabs

---

gui/package.json
gui/src/components/ContractCallForm.tsx
gui/src/components/SearchBar/Explorer.tsx
gui/src/hooks/useAllAddresses.ts
gui/src/routes/dialog/_l/tx-review.$id.tsx
gui/src/routes/home/_l/explorer/_l/addresses/index.tsx
gui/src/routes/home/_l/transfer/_l.erc20.tsx
gui/src/routes/home/_l/transfer/_l.eth.tsx
nix/package.nix
pnpm-lock.yaml

Autocomplete Addresses fields
