- .github/workflows/ci.yml
- .github/workflows/release.yml
- rust-toolchain.toml
- tauri/src/app.rs
- tauri/src/main.rs
We don't actually need nightly right now (just need to use the once_cell crate instead of the nightly-only std feature)
and this should greatly improve build caching on CI
> Using rust stable

- .eslintrc.js
- extension/global.d.ts
- gui/src/components/Settings/Wallet.tsx
- package.json
adding `tsc --noEmit` to the CI, since the release workflow keeps failling due to uncaught typescript problems
> improving yarn lint

- gui/src/components/Balances.tsx
- gui/src/components/Contracts.tsx
- gui/src/hooks/useRefreshConnections.ts
- gui/src/hooks/useRefreshNetwork.ts
- gui/src/hooks/useRefreshTransactions.ts
- tauri/src/app.rs
- tauri/src/context/block_listener.rs
- tauri/src/context/inner.rs
- tauri/src/rpc.rs
- tauri/src/store/types.rs
One of the lints was about all events in the enum being called `Refresh....`, so I renamed them for a bit more clarity
I also ended up finding the `useRefreshTransactions` hook and used it in a couple of places where the original useEffect still existed
> Solving clippy lints

- .eslintrc.js
- Cargo.lock
- gui/src/App.tsx
- gui/src/components/HomePage.tsx
- gui/src/components/NestedRoutes.tsx
- gui/src/components/Panel.tsx
- gui/src/components/QuickAccountSelect.tsx
- gui/src/components/QuickNetworkSelect.tsx
- gui/src/hooks/useKeyPress.ts
- gui/src/hooks/useMenuAction.ts
- tauri/src/app.rs
This change takes the first steps toward keyboard navigation:
* Use routes to change tabs. Using routes instead of a component's internal state means we can change tabs from anywhere. This logic will apply to everything.
* Create menubar items. The menubar allows people to set local or global shortcuts in the app. At least on macOS, you can easily map shortcuts to items in the menubar.
* Defining initial in-app shortcuts to change tabs. We can replace these later, this is just an initial step.
> Initial support for keyboard navigation

- gui/src/components/ContextMenu.tsx
- gui/src/components/Contracts.tsx
- gui/src/components/HomePage.tsx
- gui/src/components/Txs.tsx
- gui/src/hooks/useNetwork.ts
The context menu is rudimentary for now, allowing copying and opening in the set explorer. It's a complex component because it does some magic, but it's a component we can easily reuse and extend to most scenarios.
Ideally, we would use native dialogs, but it's not supported by Tauri yet, so we'll have to stick with the material component for now!
> Show context menu

- gui/src/components/HomePage.tsx
- gui/src/components/Peers.tsx
- gui/src/hooks/useRefreshPeers.ts
- tauri/src/app.rs
- tauri/src/context/inner.rs
- tauri/src/context/wallet.rs
- tauri/src/main.rs
- tauri/src/peers/commands.rs
- tauri/src/peers/global.rs
- tauri/src/peers/mod.rs
- tauri/src/types/checksummed_address.rs
- tauri/src/types/global_state.rs
- tauri/src/types/mod.rs
- tauri/src/ws.rs
This change was taken out of #163 , to simplify that PR
this changes nothing in terms of features, and settings files, because this particular field is not persisted. It also has the least interaction with other parts of the Context, so its easy to extract
> Extracts Peers out of Context

- gui/src/components/Txs.tsx
- tauri/src/db/queries.rs
- tauri/src/types/events.rs
We can now "copy to clipboard" wei values, which will copy the raw wei instead of the presented unit.
In the process, I noticed we weren't correctly tracking the wei value of transactions. So now we are
> Fixes wei value tracking; Adds "copy to clipboard" to wei values

- .github/workflows/release.yml
After adding the release-drafter action, the current release workflow became broken, since it would attempt to create a new draft
This should hopefully fix it, although the only way to be sure is to actually run it (which I will do today)
> Fixing release workflow

- .github/workflows/release.yml
- Cargo.lock
- package.json
- tauri/Cargo.toml
this is a temporary change, because libsodium-sys appears to already bundle the statically-linked binaries.
The latest release was apparently using dynamic linking, contrary to what I thought initially
> using libsodium-sys

- .github/workflows/release.yml
- .gitignore
- Justfile
- extension/manifest.json
- extension/options/index.ts
- extension/package.json
- extension/release.sh
- extension/settings.ts
Fixing #228 
This requires two different tasks:
The last one will have to be handled on the CI, at least until parcel supports firefox extensions ([which it currently doesn't](https://github.com/parcel-bundler/parcel/issues/8785))
some manual testing indicates that simply replacing `{"service_worker": "background.*.ts"}` with `{"scripts": ["background.*.ts"]}` in the output manifest seems to work
chrome and firefox currently require one or the other, there's no version of the manifest that can satisfy both
So editing the workflow to create an additional output zip, with the updated manifest can solve this
> Supporting firefox

- gui/src/components/Balances.tsx
- gui/src/components/SettingsGeneral.tsx
- gui/src/types.ts
- tauri/src/settings/mod.rs
Add a checkbox in settings to allow users to decide if they want to see empty tokens in the details ui page or not.
> hide empty tokens in details ui

- gui/src/App.tsx
- gui/src/components/Balances.tsx
- gui/src/components/ContextMenu.tsx
- gui/src/components/ProviderCurrentNetwork.tsx
- gui/src/components/ProviderNetworks.tsx
- gui/src/components/ProviderTokensBalances.tsx
- gui/src/components/QuickNetworkSelect.tsx
- gui/src/components/WagmiWrapper.tsx
- gui/src/hooks/tauri.ts
- gui/src/hooks/useCurrentNetwork.ts
- gui/src/hooks/useRefreshBalances.ts
- gui/src/hooks/useTokensBalances.ts
- gui/src/types.ts
- tauri/src/alchemy/commands.rs
- tauri/src/alchemy/global.rs
- tauri/src/alchemy/mod.rs
- tauri/src/app.rs
- tauri/src/block_listener/mod.rs
- tauri/src/db/commands.rs
- tauri/src/main.rs
- Move balances to a react context;
- Request tokens on wallet address change;
- Request tokens on network change;
- Request tokens balances every 10 min;
- Refactor wagmiWrapper to avoid side-effect config, and to be chain-aware. The wagmi wooks now need to receive the chainId, but the wrapper wont rebuild it self on network change;
- Split Networks context into two: Networks and currentNetwork. This is not that important but, splitting those two, makes things a bit more clear. On the frontend they do not really depend from each other, can avoid unnecessary renders and, because we will change the "current network" behavior in the future can be helpful on that effort.
> Live networks balances auto request

- gui/src/components/SettingsGeneral.tsx
- gui/src/types.ts
Add a text field to the UI settings to add an Alchemy api key to be used in the future to get the current account token list and balances. This is to be only used in live networks.
> add text field for alchemy api key in ui settings

- tauri/src/alchemy/error.rs
- tauri/src/alchemy/mod.rs
- tauri/src/alchemy/types.rs
- tauri/src/block_listener/expanders.rs
- tauri/src/block_listener/mod.rs
- tauri/src/db/mod.rs
- tauri/src/db/queries.rs
- tauri/src/types/events.rs
- tauri/src/types/mod.rs
The DB module was getting a bit of a mess: doing provider requests, as well as receiving alchemy-specific payloads for ERC20 balances
This refactors both of those.
* Alchemy types are now private to the Alchemy module. The `save_balances` function receives a simple tuple vector, which Alchemy needs to convert to itself
* Logic to parse events and possibly do additional provider requests has been moved to the block_listener module, since that'll likely be anvil-only for the time being
> Refactors some DB functions, and alchemy integration

- tauri/Cargo.toml
- tauri/src/crypto/mod.rs
This is yet another snippet extracted from the hd-wallet branch.
This time, adding a crypto module (as in cryptography, not cryptocurrency), which encrypts/decrypts secrets via a password
The approach was taken from https://kerkour.com/rust-file-encryption-chacha20poly1305-argon2
> Adds crypto module with Argon2 + XChaCha20Poly1305

- gui/package.json
- gui/src/components/Txs.tsx
- gui/src/types.ts
- tauri/src/db/commands.rs
- tauri/src/db/mod.rs
- tauri/src/db/pagination.rs
- yarn.lock
Since mainnet history may be too big, we need pagination in the transactions list and queries, otherwise the UI blocks for too long (e.g.: the default test account has 460 mainnet transactions)
> Paginated transaction list

- gui/src/components/BalancesList.tsx
When tokens have a balance < 0.001, this would show as 0 in the UI, which would be confusing since we have a default setting of hiding tokens with zero balance
This change makes it more explicit that the actual balance is not zero, but close to it
> Change near 0 amounts to < 0.001

- gui/src/components/ContextMenu.tsx
- gui/src/components/Modal.tsx
- gui/src/components/Txs.tsx
This prevents some weird behaviours when clicking on context menus that exist inside accordion headers
> Stopping event propagation in modals and contextmenus

- gui/src/components/WagmiWrapper.tsx
Since we were creating connectors to multiple chains, wagmi wouldn't connect to any one by default, which means wagmi hooks were actually failing (unnoticed because we aren't using them at this point)
By generating only an object for the currently connected chain, this ends up being solved
> Fixing WagmiWrapper

- tauri/src/alchemy/mod.rs
- tauri/src/alchemy/utils.rs
Batches alchemy transactions in chunks of 20, and updates the UI after each batch
this is a rudimentary approach to having some data on UI ready right away instead of waiting for the entire intial sync
> Buffering alchemy transfers and notifying UI periodically

- gui/src/components/BalancesList.tsx
- gui/src/components/IconCrypto.tsx
We're showing icons based solely on the token name, which may be a security issue since any random token may set arbitrary names.
Before shipping this feature, I'm hiding icons temporarily to better think on how to approach this
PS: The same issue arguably exists for token names. I'll handle that for now by showing the contract address (which at least makes it easier to verify), although a long-term solution will always be to create a denylist of spam tokens
> Hiding crypto icons for now

- gui/src/components/BalancesList.tsx
- tauri/src/block_listener/mod.rs
- tauri/src/db/mod.rs
This was an oversight. We broke erc20 metadata for anvil when we added alchemy support. As a result, tokenns were not showing for anvil chains
This adds it back
> Fetching ERC20 metadata on anvil

- crates/rpc/src/lib.rs
- crates/rpc/src/send_transaction.rs
- crates/rpc/src/sign_message.rs
- crates/wallets/src/hd_wallet.rs
- crates/wallets/src/json_keystore_wallet.rs
- crates/wallets/src/plaintext.rs
- crates/wallets/src/wallet.rs
This refactor has three interesting benefits:
* It now applies a Builder pattern, which allows us to no longer have `Option<T>` in the logic itself. less unwraps and error handling to go around
* It defers the signer building process until the very end, meaning we only ask for a password after the transaction has been approved. The UX of asking for a password only to later reject a transaction would not be ideal
* We can now simulate the transaction & estimate gas without having a signer at all. This will be important in impersonation wallets, where signers can't even be built
> Refactor SendTransaction / SignMessage

- bin/iron/src/app.rs
**Why:**
**How:**
Following up on the changes in https://github.com/iron-wallet/iron/commit/3541f1f9362abc05182c52df14e6fed069780bcc this PR removes the `details` item which was being added to the _go sub menu_ but not instantiated.
> fix: go submenu adding unexistent item

- Cargo.lock
- bin/iron/Cargo.toml
- bin/iron/src/app.rs
- bin/iron/src/error.rs
- crates/broadcast/src/lib.rs
- crates/dialogs/Cargo.toml
- crates/dialogs/src/error.rs
- crates/dialogs/src/global.rs
- crates/dialogs/src/handle.rs
- crates/dialogs/src/lib.rs
- crates/networks/src/error.rs
- crates/networks/src/init.rs
- crates/networks/src/lib.rs
- crates/sync/alchemy/src/error.rs
- crates/sync/anvil/src/error.rs
- crates/sync/anvil/src/global.rs
- crates/sync/anvil/src/tracker.rs
- crates/sync/src/lib.rs
- crates/types/src/lib.rs
- crates/types/src/ui_events.rs
- crates/wallets/src/error.rs
- crates/wallets/src/hd_wallet.rs
- crates/wallets/src/init.rs
- crates/wallets/src/lib.rs
- crates/ws/src/error.rs
- crates/ws/src/init.rs
- crates/ws/src/peers.rs
- crates/ws/src/server.rs
- gui/src/components/Txs.tsx
This was a low-hanging fruit. After initially introducing `iron_broadcast`, we now have a safe global way to send messages across different components. but the UI messages were still being handled by sending a `window_snd` object everywhere
This creates a new sender module for UI msgs in `iron_broadcast`, and replaces all previous `window_snd` ocurrences with it
I'm targeting this PR to the `better-fetch` branch, corresponding to #316 , because this refactor was largely motivated and dependant on what happened there
> Using iron_broadcast instead of propagating a sender object everywhere

- bin/iron/tauri.conf.json
- gui/src/App.tsx
- gui/src/components/Balances.tsx
- gui/src/components/BalancesList.tsx
- gui/src/components/CommandBar.tsx
- gui/src/components/CommandBarButton.tsx
- gui/src/components/HomePage.tsx
- gui/src/components/Navbar.tsx
- gui/src/components/QuickAddressSelect.tsx
- gui/src/components/QuickNetworkSelect.tsx
- gui/src/components/QuickWalletSelect.tsx
- gui/src/components/SettingsButton.tsx
- gui/src/components/Sidebar.tsx
- gui/src/global.d.ts
- gui/src/store/networks.ts
- gui/src/store/theme.ts
- gui/src/store/wallets.ts
In this change, we replace the tabs with a sidebar. The goal is to make Iron look more like any other desktop app while at the same time making the UI more self-explanatory.
We are also moving the dropdown selectors for wallet, address, and network to the sidebar. They have labels to make them easy to figure out, and the style change so they are less "present" in the UI.
The sidebar also has a compact mode, where the text and dropdown disappear, and we are left with just icons. This mode is nice for those who don't want Iron taking up a lot of space and only need to look up small bits of information or perform short interactions. The dropdowns disappear, but we still have the button for the command bar that can be used to click around and perform actions like changing network, wallet, or …
> Add Sidebar

- gui/src/components/HomePage.tsx
- gui/src/components/Sidebar.tsx
whenever the sidebar was edited and hot-reloaded, an error would be thrown about `TABS[0]` being uninitialized. This seems to fix it
cc/ @gabrielpoca
> Fixes sidebar's HMR

- bin/iron/tauri.conf.json
- gui/src/components/Account.tsx
- gui/src/components/HomePage.tsx
- gui/src/components/Sidebar.tsx
- gui/src/components/index.ts
- gui/src/global.d.ts
- gui/src/store/theme.ts
- Refactors sidebar to size down on `sm` breakpoint instead of `md` (makes more sense visually to me. the previous version left a lot of empty space on the right
- changes `Details` to `Account`, since the previous name no longer makes sense 
- Refactors Sidebar to no longer wrap the content (which semantically speaking was weird)
- makes the default window size smaller
> Several chores I've been piling up

- gui/src/App.tsx
- gui/src/components/CommandBarButton.tsx
- gui/src/components/HomePage.tsx
- gui/src/components/Navbar.tsx
- gui/src/components/Onboarding/Wizard.tsx
- gui/src/components/Settings/Settings.tsx
- gui/src/components/SettingsButton.tsx
- gui/src/components/Sidebar.tsx
- gui/src/hooks/index.ts
- gui/src/hooks/useOS.ts
- gui/src/store/theme.ts
This change addresses multiple minor issues:
* Changed the settings to use a sidebar instead of tabs.
* Disabled `user-select` globally so the app behaves more like a native app.
* Removed the icon from the sidebar/toolbar on mac because it's not common to see them.
* Fixed the toolbar so it's also present in the sidebar to make sure the window can be dragged when someone clicks on the top of the sidebar.
* Addressed padding inconsistencies between macOS and other systems.
* Fixed the breaking points in the settings and command line buttons.
> Sidebars and Toolbars

- extension/src/public/manifest.json
- extension/src/public/manifestv2.json
We don't use this permission (we inject scripts, but via content-script, which apparently does not require this)
Chrome web store rejected our first submission over it
> Removing unused scripting permissions

- bin/iron/src/app.rs
- bin/iron/src/commands.rs
- bin/iron/src/main.rs
- crates/ws/src/server.rs
- gui/src/App.tsx
- gui/src/components/DevBuildNotice.tsx
- gui/src/components/index.ts
- Making it clear when we're running a debug version or the actual Iron installed on the same system.
- adding the option of setting a different WS endpoint, so that we can have both debug and release versions running simultaneously
> Dev mode notice and new WS endpoint

- crates/broadcast/src/lib.rs
- crates/networks/src/lib.rs
- crates/rpc/src/lib.rs
- crates/ws/src/init.rs
- crates/ws/src/peers.rs
It turns out the `networkVersion` field is a metamask-specific field that we don't actually need. This trickles down into the even logic, where we were sending the chain name alongside the chain ID in order to feed that field.
We can safely remove it and return the stringified chain ID instead (for backwards compatibility with prior versions of the extension. The field needs to be there, but its value doesn't matter much)
> Removes network name from ChainChanged version

- Cargo.lock
- package.json
this fixes the yarn setup script, which was not working
Cargo.lock was updated when I built the app locally - iron-exchange-rates version updated to 0.5.0 automatically
> fixed extension yarn setup

- extension/e2e/test.e2e.ts
- extension/package.json
- extension/src/background/index.ts
- extension/src/content-script/index.ts
- extension/src/inpage/index.ts
- extension/src/inpage/provider.ts
- extension/src/inpage/types.ts
- gui/src/components/QuickAddressSelect.tsx
- yarn.lock
* Simplifies connection logic to remove packages such as `pump` and `object-multiplexer`, which were metamask leftovers we don't actually need
* Removes all internal state of the provider (other than `initialized` check), to simplify it even further
> Clean up extension code

- extension/src/inpage/provider.ts
I mistakenly removed these `bind`s, but they're needed.
To reproduce: the previous version couldn't connect to eip6963.org
> Fixes extension provider not working on eip6963.org

- extension/scripts/build.sh
extension build script wasn't working on linux. Fix and tested in Mac and Ubuntu.
> Extension build script now compatible with linux

- Cargo.lock
- crates/crypto/Cargo.toml
- crates/crypto/src/error.rs
- crates/crypto/src/lib.rs
Fixes a rust crash when the unlock password was incorrect.
The correct behaviour is for an `Err` to be returned to update the UI, but instead there was an `unwrap()` somewhere in there
> Fixes crash on wrong password

- Cargo.lock
- Cargo.toml
- bin/iron/Cargo.toml
- bin/iron/src/app.rs
- crates/http/Cargo.toml
- crates/http/src/init.rs
- crates/http/src/lib.rs
- crates/ws/src/server.rs
Why:
* Starting the migration proposed in issue #371
How:
* Creating a new crate in `crates/http` that spawns an Axum server.
The server for now only responds to the `/` endpoint with a "Hello
world!" message. The server runs by default at `127.0.0.1:9003` but
can be configured through an env var `IRON_HTTP_SERVER_ENDPOINT`
* Adding the new crate to `Cargo.toml`
* Calling the `init` function from the `iron-http` crate in
`bin/iron/src/app.rs`
> Add iron-http crate with initial Axum setup

- Cargo.lock
- crates/http/Cargo.toml
- crates/http/src/error.rs
- crates/http/src/init.rs
- crates/http/src/lib.rs
Why:
* Continuing the migration proposed in issue #371
How:
* Adding a `handler_rpc` function that handles JSON-RPC requests made to `/`,
using `iron_rpc::Handler`
* Replacing the temporary implementation of the router in `http/init.rs` to make use
of the new handler function
* Adding an `error.rs` with error type declarations
* Making the needed changes to `lib.rs` and `Cargo.toml`
With this change, it's now possible to use Iron as a JSON-RPC provider, via HTTP:
```js
import { ethers } from "ethers";
const provider = new ethers.JsonRpcProvider("http://127.0.0.1:9003");
console.log(await provider.getBlockNumber());
```
> Correctly respond to JSON-RPC requests on `iron-http`

- gui/src/components/AddressView.tsx
The markup on AddressView was wrong, and including a button nested inside another button
> Fixing nested btn error

- gui/src/components/DevBuildNotice.tsx
- gui/src/store/theme.ts
Addresses the two issues in the images:
> Issues with the Toolbar

- Cargo.lock
- crates/ws/Cargo.toml
Why:
* CI was failing due to vulnerability in older version of the crate
`error[vulnerability]: Tungstenite allows remote attackers to cause a denial of service`
How:
* Running the suggested command to update the dependency, `cargo update
-p tungstenite@0.20.0`, didn't work so I manually updated the `Cargo.toml`
file in the `iron-ws` crate
> Updating `tungstenite` dependency

- gui/src/components/ABIForm.tsx
Why:
* Solves #405
How:
* Including a `value` key in the params for `rpc_send_transaction` that
contains the `params.value` value or defaults to empty string
> Including `value` for payable functions in Contract interface

- gui/src/components/AddressView.tsx
Why:
* Doing a transaction was causing the TX simulation window to not open
properly
How:
* Interpolating the address passed to the `truncateEthAddress` function
to prevent JS to assume the address as an hexstring and not a string
Co-Authored-By: Resende <17102689+ZePedroResende@users.noreply.github.com>
> Fix TX simulation bug

- Cargo.lock
- crates/http/Cargo.toml
- crates/http/src/routes/mod.rs
- crates/http/src/routes/ws.rs
- crates/ws/src/lib.rs
Why:
How:
* Updating the `router` to merge all the `iron` namespaced endpoints
under `/iron`
* Adding a `get_peers_by_domain_handler` function that calls the
`ws_peers_by_domain`
* Updating the `Cargo.toml` to include the `iron-ws` crate as dependency
> Implement http endpoints for ws commands

- Cargo.lock
- crates/http/Cargo.toml
- crates/http/src/routes/forge.rs
- crates/http/src/routes/mod.rs
- crates/http/src/routes/ws.rs
- crates/ws/src/lib.rs
Why:
* Continuing adding endpoints for issue move from IPC to HTTP #371
How:
* Adding a new endpoint for the newly added `forge_get_name` command
* Renaming the `ForgeGetAbiParams` struct to `ForgeParams` in order to
be usable by both endpoints
> Implement the `/iron/forge/name` endpoint

- Cargo.lock
- crates/connections/src/commands.rs
- crates/http/Cargo.toml
- crates/http/src/error.rs
- crates/http/src/routes/connections.rs
- crates/http/src/routes/mod.rs
Why:
How:
* Adding GET and POST `/iron/connections/affinity_for` handlers
* Updating the `iron-http` router to include the new endpoints
> Implement the `iron/connections` endpoints

- crates/http/src/error.rs
- crates/http/src/routes/mod.rs
- crates/http/src/routes/networks.rs
Why:
How:
* Implementing endpoints for the `iron-networks` commands
* Updating the `iron-http` router to include the `/networks` routes
> Implement `/iron/networks/` endpoints

- Cargo.lock
- crates/http/Cargo.toml
- crates/http/src/error.rs
- crates/http/src/routes/mod.rs
- crates/http/src/routes/wallets.rs
Why:
How:
* Implementing endpoints for the `iron-wallets` commands
* Updating the `iron-http` router to include the `/wallets` routes
> Implement `/iron/wallets/` endpoints

- Cargo.lock
- crates/http/Cargo.toml
- crates/http/src/error.rs
- crates/http/src/routes/mod.rs
- crates/http/src/routes/simulator.rs
- crates/http/src/routes/wallets.rs
- crates/simulator/src/lib.rs
Why:
How:
* Implementing endpoints for the `iron-simulator` commands
* Updating the `iron-http` router to include the `/simulator` routes
> Implement `/iron/simulator/` endpoints

- Cargo.lock
- crates/http/Cargo.toml
- crates/http/src/error.rs
- crates/http/src/routes/mod.rs
- crates/http/src/routes/networks.rs
- crates/http/src/routes/settings.rs
- crates/http/src/routes/simulator.rs
- crates/http/src/routes/wallets.rs
- crates/simulator/src/lib.rs
Why:
How:
* Implementing endpoints for the `iron-settings` commands
* Updating the `iron-http` router to include the `/settings` routes
> Implement `/iron/settings/` endpoints

- crates/http/src/routes/internals.rs
- crates/http/src/routes/mod.rs
Why:
How:
* Implementing endpoints for the `iron` commands
* Updating the `iron-http` router to include the `/internals` routes
> Implement `/iron/internals/` endpoints

- Cargo.lock
- crates/http/Cargo.toml
- crates/http/src/routes/internals.rs
- crates/http/src/routes/mod.rs
- crates/http/src/routes/sync.rs
Why:
How:
* Implementing endpoints for the `iron-sync` commands
* Updating the `iron-http` router to include the `/sync` routes
> Implement `/iron/sync/` endpoints

- Cargo.lock
- crates/db/src/lib.rs
- crates/db/src/utils.rs
- crates/http/Cargo.toml
- crates/http/src/routes/db.rs
- crates/http/src/routes/internals.rs
- crates/http/src/routes/mod.rs
- crates/http/src/routes/sync.rs
Why:
How:
* Implementing endpoints for the `iron-db` commands
* Updating the `iron-http` router to include the `/db` routes
Note: This PR is different from all the others in the sense I couldn't
use the fuctions that were annotated with `#[tauri::command]` directly
due to a `tauri::State` parameter. Given that most of the functions in
the `db/commands.rs` file are wrappers around the functionality, and we
can't create a `tauri::State`, the solution was to call the `db`
functions directly, where aplicable, and copy paste the command
implementation where needed
> Implement `/iron/db/` endpoints

- crates/http/src/error.rs
- crates/http/src/routes/mod.rs
- crates/http/src/routes/transactions.rs
Why:
How:
* Adding a POST `/iron/transactions/send_transaction`
* Updating the `iron-http` router to include the `/transactions` routes
> Implement `/iron/transactions/` endpoints

- extension/scripts/build.sh
Why:
* #453
How:
* Using the `uname` command to check if the OS that is running the
script is MacOS. If it is, changing the arguments passed to `sed`
* Changing the single quotes around the substitute argument to double
quotes in order for bash string interpolation to work correctly
> Fix extension build script to be compatible with MacOS

- extension/package.json
- extension/src/background/index.ts
- yarn.lock
Previously, we had some finicky behaviour with the extension randomly disconnect, and sometimes requiring us to refresh the page twice before it would pick up the ws connection again
With the new version of `websocket-ts`, re-connecting is much smoother, and a builtin ArrayQueue is already included to buffer messages while disconnected.
This both simplifies our custom logic but also makes re-connection logic a lot more stable
> Stabilizes extension connection

- extension/scripts/build.sh
Why:
* The current version is creating a `manifest.json""` file when run on a
MacOS
How:
* Using an array to set the list of arguments and using list expansion
to set the `sed` args
> Fix extension build script

- crates/http/src/routes/settings.rs
Why:
* After a clean install, the onboarding wizard is shown. However,
there's an issue that prevents the user to either skip or finish the
onboarding. In the `Wizard.tsx` file, there's a call to the
`settings_set` endpoint that passes the `newSettings` key, and the
endpoint is expecting `new_settings`
How:
* Using the `SetSettings` struct as the type for the `set_settings`
functions in the http settings crate so that we make use of Serde's
`rename_all` to convert the params from camelCase to snake_case
> Fix stuck onboarding

- bin/iron/src/app.rs
- gui/src/components/DraggableToolbar.tsx
- gui/src/components/Navbar.tsx
- gui/src/components/Onboarding/index.tsx
- gui/src/components/index.ts
* Add a draggable element to onboarding.
* Hide the titlebar on macos.
> Hotfix: remove unexpected window title and the window not being draggable

- crates/rpc/src/error.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/send_transaction.rs
- crates/wallets/src/lib.rs
- crates/wallets/src/wallet.rs
- gui/src/components/ABIForm.tsx
This solves a long-standing issue (#426) where submitting a transaction with a different `"from"` than what that tab's connection was currently using would result in incorrect behavior (i.e. showing the wrong address on the UI)
> Better 'from' detection when submitting transactionss

- Cargo.lock
- Cargo.toml
- crates/forge/src/abi.rs
- crates/rpc/src/error.rs
- crates/rpc/src/send_transaction.rs
- crates/rpc/src/sign_message.rs
- crates/sync/anvil/src/expanders.rs
- crates/types/src/lib.rs
- crates/wallets/src/commands.rs
- crates/wallets/src/error.rs
- crates/wallets/src/lib.rs
- crates/wallets/src/signer.rs
- crates/wallets/src/wallet.rs
- crates/wallets/src/wallets/hd_wallet.rs
- crates/wallets/src/wallets/impersonator.rs
- crates/wallets/src/wallets/json_keystore_wallet.rs
- crates/wallets/src/wallets/mod.rs
- crates/wallets/src/wallets/plaintext.rs
- crates/ws/src/peers.rs
The existing signing logic doesn't fit different `Signer` types. So far, all wallets are `ethers::signer::Wallet<SigningKey>`, which is a signer that holds a private key in memory somehow.
Ledgers will use `ethers::signer::Ledger` instead.
Since these traits are not object-safe, we can't box them. And due to restrictions with `enum_dispatch` we also can't make this whole setup a generic trait. Not to mention it would greatly increase the complexity
Instead, we now have our own `iron_wallet::Signer`, which does a similar forwarding to an `enum_dispatch`, to accomodate both SigningKeys and Ledgers
> Refactors signing logic (to accomodate ledgers)

- bin/iron/src/app.rs
- crates/dialogs/src/commands.rs
- crates/dialogs/src/error.rs
- crates/dialogs/src/global.rs
- crates/dialogs/src/handle.rs
- crates/dialogs/src/lib.rs
- crates/rpc/src/send_transaction.rs
- crates/rpc/src/sign_message.rs
- crates/wallets/src/wallets/hd_wallet.rs
- crates/wallets/src/wallets/json_keystore_wallet.rs
- gui/src/components/Dialogs/MsgSign.tsx
- gui/src/hooks/useDialog.ts
Simplifies the dialog logic:
* no longer have an explicit accept/reject type. Instead, each dialog handles its own lifecycle with json messages as it sees fit (a simple `"accept"` message replaces the previous behaviour of `DialogMsg::Accept`.
* This is because the previous logic no longer had much use after the ledger integration was merged, since it increased complexity in the lifecycle of the TX review dialog
> Dialog refactor

- crates/rpc/src/send_transaction.rs
- gui/src/App.tsx
The `SendTransaction` logic would indefinitely lock on to `Wallets::read()` for the entire duration of the dialog, which means write operations on wallets would hang forever (e.g.: changing the current wallet on the main UI)
this issue would get even bigger when users close the dialog, which currently does not clean up the `SendTransaction` object (something to fix later, not as serious), since the deadlock would now be there forever
> Fies a deadlock on SendTransaction

- Cargo.lock
- bin/iron/Cargo.toml
- bin/iron/src/app.rs
- bin/iron/src/error.rs
- bin/iron/src/main.rs
- bin/iron/src/system_tray.rs
- bin/iron/src/utils.rs
- crates/broadcast/src/lib.rs
- crates/http/Cargo.toml
- crates/http/src/error.rs
- crates/http/src/init.rs
- crates/http/src/lib.rs
- crates/http/src/routes/mod.rs
- crates/http/src/routes/ui.rs
- crates/http/src/utils.rs
- crates/ws/src/server.rs
If iron is started, and a global lock file is already created, the app
won't start
instead, it will send an HTTP request to the running process asking for the main window to be open (in case it's currently hidden)
This mimics the behaviour of many modern desktop apps
> Ensure at most 1 iron instance is running

- .github/workflows/release.yml
Since the extension release job publishes to chrome/firefox stores, and versions are no replaceable, we only want to do it once a release is successfully built, otherwise we risk having to artificially increment version number for a fix
> Building extension after app

- gui/vite.config.ts
While we are not vulnerable, since we don't use tauri's updater and have no private key generated, this is an important fix to apply
Fixes https://github.com/iron-wallet/iron/security/dependabot/34
> Prevent leak of TAURI_ env variables

- Cargo.lock
- bin/iron/Cargo.toml
- bin/iron/src/app.rs
- bin/iron/src/commands.rs
- bin/iron/src/error.rs
- bin/iron/src/utils.rs
- crates/settings/Cargo.toml
- crates/settings/src/autostart.rs
- crates/settings/src/error.rs
- crates/settings/src/init.rs
- crates/settings/src/lib.rs
- gui/src/components/Settings/General.tsx
- gui/src/types/settings.ts
Adds a new general setting, which toggles application autostart
this is supposed to be OS-agnostic, although I was only able to test it in linux & macos:
* linux: creates a ~/.config/autostart/iron.desktop`
* macos: creates a `~/Library/LaunchAgents/iron.plist`, and triggers a system notification about Iron being allowed as a background app
> Autostart on boot

- gui/src/components/Settings/General.tsx
[
](url)
Should be "minimized".
> Fix typo on general settings

- Cargo.lock
- Cargo.toml
- bin/indexer/Cargo.toml
- bin/indexer/src/config.rs
- bin/indexer/src/main.rs
- bin/indexer/src/provider.rs
- bin/indexer/src/sync.rs
- iron-indexer.toml
This sets up an `iron-indexer` binary, which takes a toml configuration file
The indexer code is heavily based off of @joshstevens19 's reth-indexer, but we couldn't use it directly because we'll be indexing slightly different things (and performance certainly won't be the same, which we're fine with)
For now this doesn't actually index anything (I'm dealing with a bug, either on reth itself or in my node's config, currently re-syncing to double-check). It just loops from a specific block and logs any tx it finds where either `from` or `to` are from a given whitelist of addresses
this is a smaller piece in the larger #502
> indexer: initial setup

- Cargo.toml
This was a weird one.
Releases today were failing, and took me way too long to figure out the root cause
This is the final output of a [failed build](https://github.com/iron-wallet/iron/actions/runs/7008385498/job/19064583451):
```
Finished 2 bundles at:
/home/runner/work/iron/iron/target/release/bundle/deb/iron_1.3.0_amd64.deb
/home/runner/work/iron/iron/target/release/bundle/appimage/iron_1.3.0_amd64.AppImage
Looking for artifacts in:
/home/runner/work/iron/iron/bin/iron/target/release/bundle/deb/iron_1.3.0_amd64.deb
/home/runner/work/iron/iron/bin/iron/target/release/bundle/appimage/iron_1.3.0_amd64.AppImage
/home/runner/work/iron/iron/bin/iron/target/release/bundle/appimage/iron_1.3.0_amd64.AppImage.tar.gz
/home/runner/work/iron/iron/bin/iron/target/release/bundle/appimage/iron_1.3.0_a …
```
> Fixing tauri-apps/tauri-action uploads

- extension/src/background/index.ts
- extension/src/content-script/index.ts
This should greatly improve the UX, since extension connection was a bit finicky.
I belive it should help with the instances where we often need to reload the browser tab for the connection to be setup
> extension: close runtime port on tab unload

- crates/simulator/tests/detris.rs
- crates/wallets/src/wallet.rs
- crates/wallets/src/wallets/mod.rs
- crates/wallets/src/wallets/private_key.rs
- gui/src/components/QuickAddressSelect.tsx
- gui/src/components/Settings/Wallet/PrivateKey.tsx
- gui/src/components/Settings/Wallets.tsx
- packages/types/wallets.ts
Adds a new wallet type: raw private key.
This is the simplest of wallets, with a single key/address. Most of the logic is re-used from HDWallet (form flow for securely creating and encrypting a secret), but simplified since we don't need to even keep a list of addresses, and switching logic
The only reason this wasn't done before is because no one had asked yet. Now they did, at #564
> feat: private key wallets

- gui/src/components/Datapoint.tsx
- gui/src/components/Txs.tsx
The transaction accordion reveal animation had a problem: since the content was only loaded on opening, the initial height of the details was much smaller than after the load (since the component would just be empty)
as a result, the animation would be much shorter, and with an immediate stutter right at the end, once loading is done
the new approach renders a skeleton for each datapoint instead of skipping the component
> Using skeletons in tx view to fix reveal animation

- Justfile
Why:
* The recent change to the way Tauri is installed and managed broke the
Justfile dev command
How:
* Using `yarn tauri dev` instead of `cargo tauri dev` to run the `dev`
command
> Fix Justfile dev command

- .gitignore
- bin/iron/src/app.rs
This makes data more persistent even if we are to erase `target` and recompile the app
should solve the annoyance of having to re-sync and onboard constantly into the dev app
> Using a data dir outside of target/debug

- gui/src/components/ABIForm/ABIInput.tsx
- gui/src/components/ERC20View.tsx
Fixes a bug in input parsing where large numbers were converted to scientific notation somewhere along the way, resulting in failure to parse on the alloy-dyn-abi side
> Fixes parsing of ABIInput fields

- gui/src/routes/__root.tsx
Why:
* The `DevBuildNotice` component is using the `useInvoke` hook, that makes
use of React Suspense, but the component wasn't wrapped around a
`Suspense` component, causing the error to appear
How:
* Moving the `DevBuildNotice` component to be inside the `Suspense`
component in the component tree
> Fix starting issue related to React Suspense

- Cargo.lock
- Cargo.toml
- crates/simulator/src/evm.rs
- crates/simulator/src/types.rs
- crates/types/Cargo.toml
- crates/types/src/lib.rs
- crates/types/src/to_alloy.rs
- deny.toml
- gui/src/routes/_dialog.dialog/tx-review.$id.lazy.tsx
This brings foundry and others all the way to May 2024, removing a lot of pending incompatibility issues
Last time I tried this a couple months ago there were a lot more weird errors to solve. not sure if I was just sleep deprivated at the time, or if some later update made it a lot easier
> Updating foundry/revm/alloy

- crates/sync/alchemy/src/lib.rs
- migrations/21_clear_transactions.sql
KV Keys were being incorrectly set, resulting in duplicate records  being stored over and over
> Fixing duplicate transactions on mainnet sync

- gui/src/components/ABIForm/ABIItemForm.tsx
Why:
* Calling a view function on a contract would display as `[object
Object]` instead of the actual return value
before:
after:
> fix: Return value of view functions

- crates/dialogs/src/presets.rs
- gui/src/routes/_dialog.dialog/msg-sign.$id.tsx
This PR introduces a simple enhancement to the Sign Message dialog. It now includes a box that displays the message, formatting JSON for better readability. Additionally, I resized the dialog window to accommodate larger messages, particularly JSON. The images below illustrate examples of a raw message and a JSON message.
<div>
</div>
> Change Sign Message dialog UI

- .github/workflows/release.yml
- extension/package.json
- extension/scripts/build.sh
- package.json
- yarn.lock
mozilla's web-ext was finally updated, allowing us to solve a few security reports from github (mostly for OCD's sake, not that they're actual issues for our releases)
> updating web-ext to 8.x.x

- bin/src/utils.rs
Why:
* In MacOS, the window was not draggable
How:
* Setting the title style to `Transparent` and enabling `decorations`
> Fix title bar in MacOS

- bin/src/dialogs.rs
- bin/src/utils.rs
- gui/src/components/AppNavbar.tsx
- gui/src/components/AppSidebar.tsx
- gui/src/routes/dialog/_l.tsx
Windows are now properly draggable, eliminating the need for the native overlay
Also added a small header with a logo on all dialogs, as a quick way to get drag functionality there too
closes #839
> Fixing data-tauri-drag-region

- gui/src/components/AppSidebar.tsx
- packages/demo/src/components/app-sidebar.tsx
- packages/ui/components/ethui-logo.tsx
- packages/ui/components/shadcn/sidebar.tsx
This is just more intuitive (clicking the icon to collapse instead of the SidebarRail component), and also plays better with macos's overlay buttons (there was no good place for the previous burger icon)
> Improves sidebar collapsing & mobile logic

- bin/src/app.rs
- crates/connections/src/ctx.rs
- crates/rpc/src/error.rs
- crates/rpc/src/lib.rs
When connecting Metamask and other wallets via Rainbowkit to an unkonwn network, the request flow usually looks like:
- `wallet_switchEthereumChain`, error returned, because chain not recongnized by wallet
- `wallet_addEthereumChain` used as a reply by Rainbowkit
ethui failed to trigger the 2nd step, resulting in users having to manually adding the network, and no proper feedback coming in from the website.
According to some obscure find in metamask's source code, the only difference was the error code being returned by the json-rpc. after attempting to return that same code, the flow started working
I couldn't find any EIP or other documentation about this specific error code, so not sure it's even suposed to be official behaviour
> Fixing wallet_switchEthereumChain -> wallet_addEthereumChain flow

- bin/tauri.conf.json
Why:
* The title for the production build was still using the old name
How:
* Updating the `productName` attribute in `tauri.conf.json`
> Production build was using previous name

- .mise.toml
Why:
* The `mise` production build task was using `yarn run tauri build`,
causing Tauri to fail to build in MacOS as it doesn't have the
`--target` option
How:
* Updating the `mise.toml` task to call the `app:build` script instead
> Update mise production task

- crates/broadcast/src/lib.rs
- crates/rpc/src/methods/send_call.rs
- crates/rpc/src/methods/send_transaction.rs
- crates/wallets/src/wallets/impersonator.rs
Why:
* Using an Anvil chain and an impersonator wallet we should be able to
submit transactions, by taking advantage of the
`anvil_impersonate_account` function
* Issue #827
How:
* Checking if the network is a dev network in the `build_provider`
function of the `send_transaction.rs` to build an appropriate
`Provider`
* Refactoring the `provider` type from `InnerProvider` to `Box<dyn
Provider<Http<Client>>>` so we can make use of different providers to
send transactions
* Adding the `is_dev` function to the impersonator wallet implementation
> Allow impersonator wallets to send transactions in Anvil

- gui/src/routes/onboarding/_l/alchemy.tsx
- packages/ui/components/form.tsx
Why:
* In order to solve #877, we need a way to skip the `isDirty` attribute
for disabling the form submit button
How:
* Setting a default value of empty string for the `alchemyApiKey` value
in the Alchemy onboarding
* Adding a new prop, `skipDirty`, to the `Form.Submit`
> Update Form.Submit to allow skip dirty validation

- crates/sync/alchemy/src/client.rs
Closes #869 
only ethereum-mainnet/sepolia actually supports this. so instead of conditionally including this only for that case, might as well remove it alltogether. we'll have to revisit the idea of a custom indexer down the line if we want to enrich transaction history, but I don't see that as a priority
> No longer fetch 'internal' alchemy transfers

- bin/src/app.rs
- crates/db/src/commands.rs
- gui/src/store/useContracts.ts
Why:
* The `db_insert_contract` is making a call to Etherscan to fetch the
contract name and ABI and this causes the insertion of a manual
contract to fail if the contract is on a non-local Anvil node
How:
* Adding a `db_insert_contract_with_etherscan` to keep previous
behaviour and updating all the calls to use the new name
* Adding a `db_insert_contract` that inserts a contract without making
the call to Etherscan
> Add `db_insert_contract_with_etherscan` command

- extension/manifest/base.json
We were using the purple icon on the production extension by mistake
> Fix extension icon color

- Cargo.lock
- Cargo.toml
- crates/simulator/Cargo.toml
- crates/simulator/src/evm.rs
The dependency is still there indirectly, but this simplifies our cargo.toml
> Removes foundry-config dep

- bin/src/app.rs
- crates/rpc/src/lib.rs
- crates/sync/alchemy/src/utils.rs
- crates/sync/src/error.rs
- crates/sync/src/worker.rs
The alchemy API key would sometimes be an empty string rather than `None`, which would cause an error deep in the alchemy sync logic
> Cleanup warning about no alchemy key

- Cargo.lock
- Cargo.toml
- bin/Cargo.toml
- deny.toml
Why:
* So we can detect if a contract address is a proxy contract
How:
* Adding `ethui-proxy-detect` as a dependency
> Add proxy-detect crate as dependency

- crates/connections/src/init.rs
- crates/connections/src/store.rs
- crates/types/src/affinity.rs
If we remove a chain, but a website still has affinity to it, getting back to that website and connecting wallet would previously crash
> Clear affinities whenever a chain is removed

- bin/src/commands.rs
Why:
* The previous PR #925 introduced a bug
How:
* Reversing the `abi` and `name` assignment
> Fix proxy name and ABI assignment

- crates/networks/src/network.rs
If a websockets URL is not provided, we default to trying the same host as http with a replaced prefix
this fixes errors when adding new anvil networks for which only http is provided, but ws needed for syncing
> Defaulting ws_url to same host as http

- crates/forge/src/init.rs
This prevents some redundant lookups on forge contract matching
> Resubscribe forge on contract creation

- gui/src/components/QuickAddressSelect.tsx
- gui/src/components/QuickFastModeToggle.tsx
- gui/src/components/QuickWalletSelect.tsx
- gui/src/store/useSettings.ts
- gui/src/store/useWallets.ts
Why:
* To solve #826 and partially fix #781
How:
* Including the wallet's name when displaying in the command bar
switcher
* Adding "fast mode" text to the command bar options to toggle fast mode
* Fixing UI update issues when changing the wallet from the command bar
and toggling fast mode
> Command bar and sidebar fixes

- crates/sync/anvil/src/tracker.rs
Why:
* To fix #932
How:
* Keeping track for all anvil chains of the latest known block number
* Skipping the db reset logic when the anvil provider still knows the
saved known block number
> Save and restore sync status for Anvil chains

- crates/networks/src/lib.rs
- crates/networks/src/network.rs
When adding a new network, the anvil listener wasn't immediately reset
> Reseting network when adding/removing/changing it

- .github/workflows/pr-lint.yml
Why:
* There's a typo in the command name for `echo`
* Include `exclude-labels` in the list of labels a PR needs to include
> Fix PR lint action

- Cargo.lock
- crates/connections/src/ctx.rs
- crates/networks/src/commands.rs
- crates/networks/src/init.rs
- crates/networks/src/lib.rs
- crates/rpc/src/methods/chain_add.rs
- crates/rpc/src/methods/chain_update.rs
- crates/rpc/src/methods/send_call.rs
- crates/rpc/src/methods/send_transaction.rs
- crates/rpc/src/methods/sign_message.rs
- crates/types/Cargo.toml
- crates/types/src/lib.rs
- crates/types/src/network.rs
Why:
* In order to prevent a cyclic dependency and so we can use the
`Network` struct for sending as parameter in Network related events
How:
* Moving the `networks/src/network.rs` file to `types/src/network.rs`
* Updating references to point to the new location
* Removing `force_is_anvil` field as it is no longer used
> Move Network to `ethui_types`

- crates/broadcast/src/lib.rs
- crates/connections/src/init.rs
- crates/db/src/init.rs
- crates/networks/src/lib.rs
- crates/rpc/src/methods/chain_add.rs
- crates/rpc/src/methods/send_transaction.rs
- crates/simulator/src/commands.rs
- crates/sync/src/commands.rs
- crates/sync/src/lib.rs
- crates/types/src/network.rs
Why:
* The Network events were passing only the `chain_id`. We want to send
the entire `Network` struct so we can access other fields
How:
* Updating the declaration for `NetworkAdded`, `NetworkRemoved`,
`NetworkUpdated`, `CurrentNetworkChanged` to receive a `Network`
* Updating all the references to use the new type
> Update Network events

- bin/src/app.rs
- crates/networks/src/commands.rs
- crates/networks/src/lib.rs
- gui/package.json
- gui/src/routes/home/_l/settings/_l/networks/_l/$name.edit.tsx
- gui/src/routes/home/_l/settings/_l/networks/_l/new.tsx
- packages/types/network.ts
- yarn.lock
Why:
* Closes #982
* If we can, we should fetch the chain id from the RPC url provided when
creating a new network
* We should also prevent creating a new, or edit, a network to one with
an existing name
How:
* Adding a command to fetch a chain id from a provider http url
* Preventing network edits if network name exists
* Updating the network creation form to populate chain id field with
value returned by the provider, if available
Demo of fetching chain id from http url
https://github.com/user-attachments/assets/0745ea87-debe-4f84-b07b-bd0d962ec734
> Network form updates

- .github/dependabot.yml
Why:
* CI action for dependabot was failing with `The property '#/updates/0/ignore' of type object did not match the following type: array`
How:
* Fixing the syntax of the `ignore` field
> Fix dependabot config file

- crates/crypto/src/lib.rs
- crates/networks/src/commands.rs
- crates/networks/src/init.rs
- crates/networks/src/lib.rs
Why:
* In preparation for a future change, the Networks struct needed to be
refactored to not include the path the to file where its contents are
read
How:
* Adding a `SerializedNetworks` struct to be used as the `inner` value
of the `Networks` struct
* Updating all the calls and references to the `Networks` struct to the
new structure
> Refactor Networks to SerializedNetworks

- Cargo.lock
- crates/connections/Cargo.toml
- crates/connections/src/init.rs
- crates/connections/src/lib.rs
- crates/connections/src/migrations.rs
- crates/connections/src/store.rs
Why:
* Similar to the networks, the connections settings are also written to
a file that needs to be versioned
How:
* Replicating the migration logic we did for the networks json file
> Add migrations to connections

- gui/src/hooks/useNoticeNewVersion.tsx
Why:
* The Download button warning about new releases should point to the new
landing page, https://ethui.dev
How:
* Updating the URL
> Update new release download url

- crates/networks/src/commands.rs
- crates/networks/src/lib.rs
- crates/networks/src/migrations.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/methods/chain_add.rs
- crates/rpc/src/methods/chain_update.rs
- crates/types/src/dedup_chain_id.rs
- crates/types/src/lib.rs
- crates/types/src/network.rs
- crates/types/src/new_network_params.rs
Why:
* #1040
How:
* Adding a new field to the `Network` struct, `deduplication_id`
intended to distinguish between multiple chains with the same chain
id
* Adding a `internal_id` function to `Networks` to retrieve the tuple
compose of chain id and deduplication id
* Adding `get_network_by_name` and `chain_id_count` to `Networks`
* Updating `ChainAdd` and `ChainUpdate` functions to take into account
the deduplication id
* Adding a migration to handle the update to `networks.json`
> Add internal_id field to Networks

- crates/connections/src/commands.rs
- crates/connections/src/ctx.rs
- crates/connections/src/migrations.rs
- crates/connections/src/store.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/methods/chain_add.rs
- crates/types/src/affinity.rs
- gui/src/routes/home/_l/connections.tsx
- packages/types/index.ts
Why:
* We need to include the dedup id to the affinities
How:
* Adding a migration to replace the chain_id with the internal_id
* Replacing chain_id with the new internal_id in the affinities
reference
> Add dedup_id migration to affinities

- crates/broadcast/src/lib.rs
- crates/connections/src/commands.rs
- crates/connections/src/ctx.rs
- crates/connections/src/init.rs
- crates/connections/src/store.rs
- crates/networks/src/init.rs
- crates/networks/src/lib.rs
- crates/rpc/src/methods/chain_update.rs
- crates/types/src/affinity.rs
- crates/types/src/lib.rs
- crates/types/src/network.rs
- crates/ws/src/init.rs
- crates/ws/src/peers.rs
Why:
* Solves #1041
How:
* Adding `set_current_by_internal_id` and replacing some usages of
`set_current_by_id`
* Updating `ChainChanged` event to receive the `internal_id` tuple
* Updating affinities and networks to use `internal_id` instead of
`chain_id`
> Replacing `chain_id` as the network identifier with `internal_id`

- crates/broadcast/src/lib.rs
- crates/connections/src/commands.rs
- crates/connections/src/ctx.rs
- crates/connections/src/migrations.rs
- crates/networks/src/migrations.rs
- crates/types/src/affinity.rs
- crates/types/src/dedup_chain_id.rs
- crates/types/src/network.rs
- crates/ws/src/peers.rs
- packages/types/network.ts
Why:
* DedupChainId should be a struct to make it impossible to send a random
tuple without explicit casting
How:
* Refactoring the `DedupChainId` type into a struct
* Adding `Into` implementations to convert between tuples and this type
* Converting usages of the `DedupChainId` into the struct format
> Refactor DedupChainId into a struct

- crates/sync/anvil/src/tracker.rs
Unsure if this is an issue in alloy or anvil, but it's an issue nonetheless
our anvil sync was missing blocks.
more details in https://github.com/alloy-rs/alloy/issues/2188
> Fixes an alloy or anvil issue with block subscriptions

- crates/forge/src/actor.rs
- crates/rpc/src/methods/sign_message.rs
- crates/types/src/events.rs
The change to rust nightly caused a new lint to show up, about an enum that has a disproportionately large variant
> Boxes a large enum variant

- .cargo/config.toml
- .github/workflows/release.yml
- .github/workflows/rust.yml
- .mise.toml
- Cargo.toml
- crates/forge/src/actor.rs
- crates/rpc/src/methods/sign_message.rs
- crates/types/src/events.rs
- rust-toolchain.toml
This provides access to a few quality-of-life improvements, such as the ability to use the [new parallel frontend](https://blog.rust-lang.org/2023/11/09/parallel-rustc.html), and [cranelift](https://cranelift.dev/)
in total, this reduces by build times (from scratch) from 1m20s down to 50s!
> Moving to rust nightly

- gui/src/routes/dialog/_l/tx-review.$id.tsx
Fixes https://github.com/ethui/ethui/issues/1110
This happened because transfers and approvals happen to have the same event payload, and apparently viem doesn't validate that `topic[0]` should match when decoding a log
> Fixing incorrectly displayed erc20 transfer

- bin/src/app.rs
- bin/src/commands.rs
- crates/networks/src/commands.rs
Why:
* The `add_contract` command was checking if the current network was a
non-anvil chain before checking for proxy implementation, instead of
using the network selected in the dialog
How:
* Calling `is_dev` in the Network instead of reading the value from the
`networks_is_dev` function that checks the current network
> Fix add contract network

- gui/src/routes/dialog/_l/tx-review.$id.tsx
When submitting ERC721 transfers, since the log topic is the same as an ERC20, the existing viem logic was getting confused and throwing an error
> Fix incorrect parsing of ERC20 logs

- packages/form/src/AbiItemForm.tsx
- packages/form/src/AbiItemFormWithPreview.tsx
There was a bug introduced in a prior version where a function call with  no inputs would result in `data: undefined`
> Fix AbiItemForm when there are no inputs

- crates/connections/src/migrations.rs
- crates/db/src/queries/chain_tip.rs
- crates/db/src/queries/contracts.rs
- crates/db/src/queries/erc1155.rs
- crates/db/src/queries/erc721.rs
- crates/db/src/queries/native_balance.rs
- crates/db/src/queries/transactions.rs
- crates/ws/src/server.rs
Why:
* The latest nightly release includes a new rule
https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
How:
* Inlining all variables in `format!` macro calls
> Fix clippy uninlined format warnings

- crates/rpc/src/methods/chain_add.rs
- crates/rpc/src/methods/chain_update.rs
When adding new chains, if `blockExplorerUrls: null`, we should treat in the same way as `blockExplorerUrls: []`.
The previous code would just fail to deserialize the field and error out on the request
> blockExplorerUrls should be optional

- crates/settings/src/onboarding.rs
Why:
* The step for the `OnboardingStep::Etherscan` was missing from the
function that sets the onboarding to finished, causing the
`is_all_finished` function to wrongly assume all the onboarding steps
were completed
How:
* Adding the missing step to `steps`
> Fix onboarding finish flow

- bin/src/windows/mod.rs
Why:
* Closes #1231
How:
* Setting the minimum inner window size, on MacOS, to be 500x375
> Set minimum window size

- .sqlx/query-d252b85cc9a994333c656a26098634fda678998e854e48c50a478105f68b0a5b.json
- bin/src/commands.rs
- crates/db/src/queries/contracts.rs
Why:
* The changes made in #1240 made the removal of a proxy contract from
the UI break. Previously we were checking if the contract to be
removed had a proxy and recursing backwards from the implementation
How:
* Updating `get_proxy` to get the `proxy_for` address for a contract
instead of the `proxied_by` address, so we can recurse from proxy to
implementation
> Fix removing proxy contract

- Cargo.lock
Why:
* There's a new `libusb` release, `1.0.29`. The linker with the previous
`cc` version was still attempting to search for the previous version
in the system folders. After tracking the issue back to the `cc` crate
an update of this package solves the issue
How:
* Running `cargo update cc` to update the `cc` dependency
> Update `cc` dependency to fix local Mac build

- crates/sync/anvil/src/tracker.rs
When a anvil provider isn't available , the watcher spams requests until it is started. 
By adding a exponential back-off to the request we can throttle this request when it's not connected while allowing the watcher to keep pooling for a potential anvil.
> Add exponencial backoff when checking for new blocks

- mprocs.yaml
We often need to work on multiple of these components simultaneously, so it's useful to have a way to start this whole stack in one command
> mprocs.yaml for easy startup app + ui + demo + explorer

- gui/src/components/QuickFastModeToggle.tsx
- gui/src/store/useSettings.ts
Fast mode would initially render to false, and would trigger a submission with that value, resulting in the value not persisting across restarts
> Fix fast mode initial rendering

- crates/connections/src/ctx.rs
- crates/connections/src/permissions.rs
- crates/proxy-detect/src/lib.rs
- crates/rpc/src/lib.rs
while we don't really use these permissions at the moment, this will silence an error on clients whenever the wallet is disconnected
> wallet_revokePermissions endpoint
